Repository gearbot/GearBot, pull requests merged in 2019-07, with the labels that each got.

#246 Fix args erroring
  GearBot/Util/DashConfig.py
Labels: bug

#249 Fix erroring when adding ignored users
  GearBot/Cogs/Serveradmin.py
Labels: bug fix

#241 Don't error when banning someone higher up
  GearBot/Cogs/Moderation.py
Labels: bug fix

#242 Allow trusted roles and users to post invites
  GearBot/Cogs/Censor.py
  GearBot/Cogs/Serveradmin.py
  GearBot/Util/Configuration.py
  GearBot/Util/Permissioncheckers.py
  config/template.json
  lang/en_US.json
Labels: new feature

#251 Add mass unban command.
  GearBot/Cogs/Moderation.py
  lang/en_US.json
Labels: new feature

#257 Dashboard outage monitoring
  GearBot/Cogs/DashLink.py
  config/master.json.example
Labels: new feature

#256 Add Verification Level command
  GearBot/Cogs/Moderation.py
  GearBot/Util/GearbotLogging.py
  lang/en_US.json
Labels: new feature
